version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_PASSWORD=Namas1234
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - spring-cloud-network
  gifbackend:
    container_name: gif-backend
    build:
      context: .
      dockerfile: Dockerfile
    image: gif-generator-backend:latest
    environment:
      spring.datasource.url: jdbc:postgresql://postgres:5432/gifgenerator
    ports:
      - "8080:8080"
    volumes:
      - ./gifgenerator:/opt/
    working_dir: /opt/
    networks:
      - spring-cloud-network
  giffrontend:
    container_name: gif-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    image: gif-generator-frontend:latest
    environment:
      spring.datasource.url: jdbc:postgresql://postgres:5432/gifgenerator
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/opt/frontend
    working_dir: /opt/frontend
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge
volumes:
  data: { }